# Generated by Django 4.0.3 on 2022-04-16 14:55

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='', verbose_name='photo de profil'),
        ),
    ]
