# Generated by Django 4.0.3 on 2022-04-09 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lettre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ville', models.CharField(max_length=128)),
                ('destinateur', models.CharField(max_length=128)),
                ('objet', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
                ('lettre', models.TextField(max_length=512, verbose_name='lettre de motivation')),
                ('jointe', models.CharField(max_length=128, verbose_name='piece jointe')),
                ('date_edit', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('usercv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('MASCULIN', 'Masculin'), ('FEMININ', 'Feminin')], max_length=30)),
                ('matrimoniale', models.CharField(choices=[('Célibataire', 'Celibataire'), ('Mariée', 'Mariee'), ('Veuve', 'Veuve'), ('Divorcée', 'Divorcee')], max_length=50, verbose_name='situation matrimoniale')),
                ('enfant', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=128, verbose_name='numéro de téléphone')),
                ('formation', models.TextField(max_length=256)),
                ('competence', models.CharField(blank=True, max_length=128, null=True)),
                ('experience_A', models.TextField(blank=True, max_length=256, null=True, verbose_name='Experience Académique')),
                ('experience_P', models.TextField(blank=True, max_length=256, null=True, verbose_name='Experience Professionnelle')),
                ('langue', models.CharField(default='anglais:faible;francais:moyen;chinois:parfait', max_length=128, verbose_name='langue parlée')),
                ('certifications', models.TextField(blank=True, max_length=128, null=True)),
                ('reference', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=128, null=True)),
                ('date_edit', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('usercv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
