# Generated by Django 4.0.3 on 2022-04-10 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cvblog', '0002_cv_nomcv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomuser', models.CharField(default='Administrateur', max_length=128)),
                ('message', models.TextField(max_length=512)),
                ('deactive', models.BooleanField(default=True)),
                ('date_edit', models.DateTimeField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 4, 10, 11, 33, 48, 816874, tzinfo=utc))),
                ('usercv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
